// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtzL2r-1fRIMVLfG4xmKLHZ2i0MeM8rmg',
    appId: '1:787966118732:web:4faa7c6051e1c0f7775de9',
    messagingSenderId: '787966118732',
    projectId: 'final-exam-e2f24',
    authDomain: 'final-exam-e2f24.firebaseapp.com',
    storageBucket: 'final-exam-e2f24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD__lPxK9U4C6N0gp1ZCG9xlRmJ1cHVaU',
    appId: '1:787966118732:android:d09f802a51c41ed4775de9',
    messagingSenderId: '787966118732',
    projectId: 'final-exam-e2f24',
    storageBucket: 'final-exam-e2f24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiBgvTGwuaEqcO_GKyRx6S4Y-7-fB41GI',
    appId: '1:787966118732:ios:356189fa506ad473775de9',
    messagingSenderId: '787966118732',
    projectId: 'final-exam-e2f24',
    storageBucket: 'final-exam-e2f24.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiBgvTGwuaEqcO_GKyRx6S4Y-7-fB41GI',
    appId: '1:787966118732:ios:356189fa506ad473775de9',
    messagingSenderId: '787966118732',
    projectId: 'final-exam-e2f24',
    storageBucket: 'final-exam-e2f24.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtzL2r-1fRIMVLfG4xmKLHZ2i0MeM8rmg',
    appId: '1:787966118732:web:d4fb971d46feef58775de9',
    messagingSenderId: '787966118732',
    projectId: 'final-exam-e2f24',
    authDomain: 'final-exam-e2f24.firebaseapp.com',
    storageBucket: 'final-exam-e2f24.firebasestorage.app',
  );
}
